build:
	cd test && make build

clean:
	cd test && make clean
	cd story && make clean

run:
	cd test && make run

plot:
	cd test && make plot

story:
	cd story && make report

.PHONY: build run plot story clean
