build:
	cd test && make build

clean:
	cd test && make clean
	cd report && make clean

run:
	cd test && make run

plot:
	cd test && make plot

report:
	cd report && make report

.PHONY: build run plot report clean
